version: "2"
linters:
  settings:
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-ST1005"] # golangci-lint's default, we add -ST1005
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
