---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# NOTE: The Packit copr_build tasks help to check if every commit builds on
# supported Fedora and CentOS Stream arches.
# They do not block the current Cirrus-based workflow.

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/
# and
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/

specfile_path: rpm/skopeo.spec
upstream_tag_template: v{version}

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    srpm_build_deps:
      - make

  - <<: *copr
    # Run on commit to main branch
    trigger: commit
    branch: main
    project: podman-next

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all
    actions:
        pre-sync:
          - "bash rpm/update-spec-provides.sh"

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
