---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# NOTE: The Packit copr_build tasks help to check if every commit builds on
# supported Fedora and CentOS Stream arches.
# They do not block the current Cirrus-based workflow.

specfile_path: rpm/skopeo.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
